language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - mysql

sudo: false

env:
  - PHALCON_VERSION="2.1.x"
  - PHALCON_VERSION="2.0.x"
  - PHALCON_VERSION="phalcon-v2.0.9"

before_script:
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && make install && phpenv config-add ../unit-tests/ci/phalcon.ini
  - php -r 'echo \Phalcon\Version::get()."\n";'
  - cd ../..


script: phpunit
